---
title: "덜 강압적인 정신과 치료를 향하여: 급성 초조 관리에서 인권의 이상과 임상적 현실을 잇다"
author: "Anselm Jeong"
bibliography: references.bib
format: docx
---

# I. 서론

정신과 치료 환경에서 발생하는 급성 초조(acute agitation)와 폭력은 환자와 이들을 돌보는 의료진 모두에게 심각한 도전 과제가 된다. 이러한 상황은 순식간에 악화할 수 있어 합리적인 의사 결정을 내릴만한 여유가 주어지지 않으며, 자칫하면 의료진은 물론 환자 본인의 신체적 위해를 초래하고, 치료 환경을 붕괴시킬 위험이 있다. 게다가 환자와 의료진의 안전을 도모한다는 목표와 더불어, 환자의 권리, 존엄성 및 자율성을 존중해야 한다는, 어쩌면 서로 상반되는 목표 사이의 긴장과 모순을 솜씨 있게 조율해야만 한다. 이 근본적인 난제는 정신과 임상에서 급성 초조/폭력 사태의 치료와 관리를 둘러싸고 벌어지는 치열한 논쟁의 바탕이 된다.

이러한 응급 상황에서 사용되는 주된 치료적 조치 중 하나는 흔히 "화학적 억제(chemical restraint)"라고 불린다. 이 용어 자체가 이미 윤리적 딜레마를 시사하며, 역사적으로도 깊은 부정적인 의미를 내포하고 있다. 비판가들은, 좀더 부드러운 방안으로도 충분히 진정시킬 수 있는 상황에서 의료진의 편의를 위해 침습적인 수단이 너무 자주 사용된다며 정당한 우려를 표한다. 그러나 이러한 비판의 핵심이 치료가 효과적이고 안전했는지 여부보다는, 그저 환자의 자율성과 존엄성을 침해하지 않았느냐에 맞춰지는 경우가 많다.

정신과 치료에서 화학적 억제를 포함한 강압적인 관행을 근절해야 한다는 열망은 임상가들 또한 널리 공유하고 지지하는 바이다. 그러나 이 이상을 급성기 임상 현장에 적용하고자 할 때, 현실과의 괴리가 심각하게 다가온다. 극심한 초조 상태에 놓인 환자는 의사 결정 능력이 일시적으로, 그리고 현저하게 손상되는 경우가 많다. 이 위기 순간에 "원치 않는 치료를 받지 않을 자유"라는 환자의 권리를 지키기 위해 개입하지 않고 물러서는 것은, 환자 자신과 주변 사람들의 신체적 안전을 지켜야 한다는 또 다른 근본적인 권리를 망각하는 태도일 것이다. 이러한 시각에서 볼 때 이 딜레마는 단순히 "의학적 관행 대 인권 침해"이라는 표면적 충돌이 아니라, 복수의 인권 사이에서 순간순간의 우선순위를 누군가는 정해야만 한다는 딜레마로 이해하는 것이 보다 타당할 것이다.

이에 더하여 고려해야할 점은, 초조/폭력 상황에 대한 개입의 여파는 상황이 해결되었다고 끝나는 것이 아니라, 상당히 오랫동안 심리적 파장으로 남아 고통을 초래할 수 있다는 점이다. 화학적 억제나 격리/강박은 단기적 안전을 제공해 주지만, 장기적으로 환자와 의료진 사이의 신뢰를 갉아먹어 향후 치료 관계에 해를 끼칠 소지가 있다. 또한 강압적인 처치 과정을 지켜보거나, 사후에 환자로부터 비난을 받게 되는 가족들이 트라우마를 경험할 수 있으며, 원치 않는 조치를 반복적으로 실행해야 하는 의료진 역시 빈번하게 도덕적 고통을 느낀다. 이는 궁극적으로 치료적 환경과 회복의 과정 자체를 훼손할 수 있다 (• [10.1513/AnnalsATS.202006-738OC](https://doi.org/10.1513/annalsats.202006-738oc)).

정신과 치료에서 강압적 개입을 최소화해야 한다는 궁극적인 목표를 전적으로 공유하지만, 이를 달성하려면 급성 정신과 응급 상황의 임상적 현실을 고려하고 환자의 자율성만큼이나 안전을 동등하게 중시하는 "현실적인 대안"이 필요할 것이다. 본 소고는 인권 차원의 이상과 임상적 현실 사이의 간극을 살피고 둘 사이에 타협점을 모색하고자 한다. 이를 위해 먼저 역사적, 법률적, 사회정치적 관점에서 화학적 강박이 갖는 인권 침해의 여지를 살피고, 그로 인해 발생한 부정적 인식을 고찰할 것이다. 그 후, 새롭게 등장하는 덜 침습적인 접근법이 정신과적 사전의료의향서(psychiatric advance directives) 및 적극적 조기 개입 전략과 결합되었을 때, 환자의 안전을 타협하지 않으면서도 강압의 부담을 줄여나가는 길을 찾을 수 있음을 제안하고자 한다.