---
title: "덜 강압적인 정신과 치료를 향하여: 급성 초조 관리에서 인권의 이상과 임상적 현실을 잇다"
author: "Anselm Jeong"
format: docx
bibliography: references.bib
---


미국 연방 보건복지부 산하 메디케어 및 메디케이드 서비스 센터 지침에 따르면, 화학적 강박은 "환자의 상태에 대한 표준적인 치료나 용량이 아니면서, 환자의 행동을 관리하거나 이동의 자유를 제한하기 위해 사용되는 약물 또는 투약"으로 정의된다. ([https://www.cms.gov/Medicare/Provider-Enrollment-and-Certification/SurveyCertificationGenInfo/downloads/scletter08-18.pdf](https://www.cms.gov/Medicare/Provider-Enrollment-and-Certification/SurveyCertificationGenInfo/downloads/scletter08-18.pdf)) 이러한 정의는 행동 통제의 목적과 적절한 의학적 치료 사이의 구분을 명확히 강조한다. 그러나 정신건강 종사자들의 관점에서 볼 때, 이 정의는 지나치게 부정적인 뉘앙스를 띠고 있다. 마치 화학적 강박이 표준적인 치료가 아니며, 가급적 피해야 할 임시방편으로 못 박아 버린다.([**10.1176/appi.ps.51.6.717](https://doi.org/10.1176/appi.ps.51.6.717))** 게다가 현재 통용되는 화학적 강박이 주로 항정신병 약물을 비경구로 사용하는 경우를 지칭한다는 점을 고려하면, 표준적인 약물 투여마저도 그 목적에 따라 화학적 강박으로 취급될 수 있는 여지가 있다.( • [10.1007/s00127-024-02739-6](https://doi.org/10.1007/s00127-024-02739-6))

**초창기의 화학적 강박**

항정신병 약물이 등장하기 전에는 아편이나 모르핀 같은 중독성 물질뿐만 아니라 장뇌(camphor), 브롬화물(bromide), 하이오신(hyoscine), 파랄데히드(paraldehyde) 등이 화학적 강박을 위해 사용되었다. 19세기 중반 클로랄 하이드레이트(chloral hydrate)가, 20세기 초 바르비투르염(barbiturates)과 페노바르비탈(phenobarbital)이 개발된 이후에는, 이들 마취/진정제가 동일한 목적으로 널리 사용되었다.{Shorter, 1997 #4; Lopez-Munoz, 2005 #5} 하지만 이들 약물은 치료 지수(therapeutic index)가 매우 낮아, 부작용에 시달리거나 자칫하면 생명을 위협할 수도 있었다. 

1950년대 항정신병 약물이 도입되면서 약물의 사용이 보다 안전해졌으며, 정신과 치료에 상존하던 물리적 구속 등 강압적인 요소들이 극적으로 감소했다. 그러나 1960년대와 70년대에 이르러 인권에 대한 인식이 크게 고조되는 중대한 변화가 일어났다. 이에 따라 1980년대에는 화학적 강박을 포함한 모든 강압적 치료를 제한하는 지침과 정책들이 마련되었다. 비정형 항정신병 약물의 등장으로 한층 더 안전한 대안이 열리는 듯했으나, 새로운 부작용과 높은 비용 문제로 인해 널리 쓰이지 못하면서, 인권 문제는 여전히 미완의 과제로 남았다. 이런 와중에 2000년대 들어 유엔 장애인권리협약(CRPD)이 촉매제 역할을 하면서, 강압적 치료에 대한 규제를 강화하고 보고를 의무화하는 움직임이 거세게 일었다. 이러한 흐름은 환자의 권리 수호를 향한 시대적 강조를 여실히 보여주는 것이었다.{Fiala-Butora, 2024 #7}

**급속 진정(Rapid Tranquilization)과 화학적 억제**

화학적 강박은 흔히 "급속 진정(rapid tranquilization)"과 혼용되곤 하지만 미묘한 차이가 있다.{Allison, 2014 #8} "급속 진정"이라는 용어는 1971년 폴락(Polak)과 레이콥(Laycob)이 발표한 논문에서 비롯되었는데, 급성 조현병 환자에게 클로르프로마진을 고용량으로 투여하여 6시간 만에 진정시킨 사례를 보고하고 있다. 진정 효과가 그야말로 치료를 앞당기는 것인지, 아니면 그저 약물의 부작용일 뿐인지는 논란의 여지가 있다.{Currier, 2003 #10} 용어를 사용한 저자들은 질병 치료 측면을 강조하고 있지만, "진정"이라는 용어는 여전히 부정적인 뉘앙스를 지닌다. 일례로 미국 정신의학의 아버지로 인정받는 벤저민 러시(Benjamin Rush)는 환자를 의자에 앉힌 후 고속으로 회전시키는 "진정 의자(tranquillization chair)"를 도입하였다. 이 시기를 기점으로 "진정제(tranquillizer)"라는 단어는 초조한 환자를 가라앉히기 위해 쓰이는 다양한 종류의 억압적인 방법을 가리키는 은어처럼 굳어졌다.

항정신병 약물이 지닌 안정화 효과가 비특이적인 진정 작용이 아니라 항도파민성 효과에 기인한다는 시각이 싹트고 있었지만, 이 약물들의 진정한 본질을 두고 계속해서 끈질긴 논쟁이 이어졌다. 즉, 이 약들이 단지 "화학적인 구속복(chemical straightjackets)"에 불과한 것인가, 아니면 근본적인 치료 수단인가라는 질문이었다.{Szasz, 1957 #11}
